### ISSUE TITLE
Unexpected behavior in default configuration

### ISSUE THREAD

**Issue by dgilperez** [intercom/intercom-rails#135]
Hi, 

I was experiencing a tricky issue in one of my projects, where sometimes we were receiving messages that apparently came from a certain user, when they not. After digging into it, we found that it has to do with intercom-rails' default configuration: 

    # == Current user method/variable
    # The method/variable that contains the logged in user in your controllers.
    # If it is `current_user` or `@user`, then you can ignore this
    #
    # config.user.current = Proc.new { current_user }

Well, we shouldn't have ignored that. We have some pages where, for unlogged users, we set the variable @user (a public view for /users/1, for example). In that case, any unlogged user will result in Intercom believing that there is a logged user (`@user`, the user being viewed), and messages will be sent appearing to come from him of her. That appears to me to be quite a common case scenario.

I think that is extremely unexpected. I suggest that you either you remove the default and force that option to be set, or remove `@user` from the default. Or, at the very least, set up a clearer message and warning. 

Thanks!

**Comment by javvarcar** [comment]
Same here. Users are receiving wrong messages in users/:id. I think '@user' is not a good choice as default user for Intercom.

**Comment by choran** [comment]
Hi dgilperez,
Yes, I can see how this can be confusing. We have since updated the troubleshooting section on the Readme page in relation to the default configuration. It is also near the top of the Readme page now. Not sure it was there previously when you encountered this issue. We feel that making sure it is visible on the Readme page is the best way to alert people to this default setting. 
Thanks for the feedback. We are also trialing a developer forum where you can discuss issues like this with other developers. You can find this [**here**](https://gitter.im/intercom/intercom-rails). It might be a good way to discuss these issues with other people using the Intercom Rails Plugin. Otherwise feel free to open another issue if you are still having issues with this.
Thanks
Cathal
