### ISSUE TITLE
Use GlobalID rather than id attribute as company ID

### ISSUE THREAD

**Issue by scpike** [intercom/intercom-rails#158]
Our application allows users to be tied to companies of different types (e.g., "Buyers" and "Sellers" in a marketplace). Those companies live in separate tables with primary keys `id` that can overlap. The intercom-rails library sends just the id attribute as the key, so our users are being linked to the wrong companies when the keys conflict.

Rails 4.2 added the GobalID (https://github.com/rails/globalid) concept to address this problem by including the class name in the ID:

``` 
   s = Seller.first 
   s.id # 1
   s.to_global_id.to_s # gid://appname/Seller/1
```

Can I configure the library as-is to use these IDs for my application? Should you change the default for new applications to use global IDs rather than ID?

**Comment by choran** [comment]
Hi scpike,
I don't see any reason why you could not use this to set a unique user_id for users. Could you also use your table names to set this? i.e. table_name/id? The issue seems to relate to the fact that you have separate tables so I don't think we would consider using the global IDs at present. If you have any problems with this please let us know via team@intercom.io with any errors and code examples you are using. Alternatively, we are trialing a developer forum via [Gitter](https://gitter.im/intercom/intercom-rails) at present so you could check in there to see if any other developers have experienced the same issues.

**Comment by scpike** [comment]
@choran I'm not talking about user IDs, I'm talking about company IDs (users are linked to companies). Does that make sense?

**Comment by choran** [comment]
@scpike I still think it should be possible whether it is the user_id or the company_id. I might be missing something but I can't think of how this would be a problem. Are the primary IDs which are overlapping your own IDs? i.e. they are not user or company IDs? How do you choose which table to update?

**Comment by scpike** [comment]
@choran Sending "table_name/id" as the company's ID would be great (that's effectively what GlobalID generates). I'm not sure how to do that, though. It seems like `id` is fairly embedded in the `Proxy` -> `Company` object model, e.g., https://github.com/intercom/intercom-rails/blob/master/lib/intercom-rails/proxy.rb#L26

**Comment by choran** [comment]
@scpike I am not sure this would work. If you change the to_hash then I dont think it would match any of the companies you have currently stored? When I was referring to setting a unique ID I was thinking that you could change the attribute of the company object itself. i.e you could set the company ID to a unique ID of table_name_id. In this way you would not need to change any of the rails code since the ID it would generate would be unique. Is there some issue preventing you from setting your company IDs in this way?
