### ISSUE TITLE
Multi user tagging is not working

### ISSUE THREAD

**Issue by peddinti** [intercom/intercom-rails#179]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-rails version: 3.4.0
  - Rails version: 3.2.13

## Expected behavior
All users muse be tagged with the corresponding tag
## Actual behavior
None of the users are getting tagged. But if i request one user at a time, they are getting tagged
## Steps to reproduce
 1.  Get multiple user emails
 2.  IntercomClient.tags.tag(name: tag_name, users: [users.map{|user| {email: user.email}]) - Not Working
 3. users.each do |user|
        IntercomClient.tags.tag(name: tag_name, users: [{email: user.email})
    end
   -- Works
## Logs

**Comment by Skaelv** [comment]
Hey, seems to me that this issue is not related to intercom-rails but to [intercom-ruby](https://github.com/intercom/intercom-ruby) am I correct ?
intercom-rails's purpose is to install the widget on a rails app. 
intercom-ruby is an API wrapper and it seems what you are reporting is related to this repo.
