### ISSUE TITLE
When will intercom-rails support Personal Access Tokens?

### ISSUE THREAD

**Issue by jolim** [intercom/intercom-rails#237]
API Keys are supposed to be phased out in January 2017. Is there a path to supporting Personal Access Tokens for this app?

**Comment by Skaelv** [comment]
Why do you need personal access tokens in intercom-rails? You should use intercom-ruby for any API related job.

**Comment by jolim** [comment]
Ah. Thanks. This issue belongs with intercom-ruby, not this one. Thanks for the prompt reply.

**Comment by schultzy51** [comment]
Access Tokens are replacing API keys entirely.  Secure mode uses the api key, which I believe will stop working after the end of this month.

**Comment by Skaelv** [comment]
Hey @schultzy51 ! 
Secure mode and Api Keys are two different concepts. You have nothing to worry about concerning secure mode we are not deprecating it.

**Comment by schultzy51** [comment]
But secure mode uses the api_key (secret) as the key in the hexdigest.

`OpenSSL::HMAC.hexdigest("sha256", secret, (user_details[:user_id] || user_details[:email]).to_s)`

**Comment by Skaelv** [comment]
It's not a proper api_key but a secure_mode secret key which are two different concepts. I know it's a bit confusing 😬

**Comment by Skaelv** [comment]
You can get your secure mode secret from https://app.intercom.com/a/apps/_/settings/web
What we are deprecating is https://app.intercom.com/a/apps/_/settings/api-keys

**Comment by schultzy51** [comment]
Interesting, looks like of some documentation is old then.

The iOS and Android documentation still reference using the api key rather than a separate secret just for secure mode.

https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enabling-secure-mode-on-intercom-for-android
https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enabling-secure-mode-in-intercom-for-ios

While web and rails documentation reference the secure mode secret.

https://app.intercom.io/a/apps/udlhpr9r/guide/web_integration/web_integration_secure_mode

From this page you can get to all those links about secure mode.
https://docs.intercom.com/configure-intercom-for-your-product-or-site#staying-secure

Thanks for your help!

**Comment by Skaelv** [comment]
I confirm we are not deprecating iOS and Android api keys. We are only deprecating API Keys to access the REST API.

**Comment by summera** [comment]
@Skaelv I'm a bit confused here. I got a notice today saying "to replace your API Keys with "Access Tokens" before April 16". Does this mean that for `config.api_secret` I should use an access token instead of the api secret from the API Keys we have been using? And should I leave `config.app_id` blank? Or is this deprecation somehow not affecting `intercom-rails` and we can leave our `app_id` and `app_secret` as they are even though they are being deprecated?

**Comment by summera** [comment]
@Skaelv I was actually confused here on the difference in api keys and secrets and came to the realization that it is not using api keys. I think it may be helpful to add something in the README about the "secret" being the identity verification for web to clear this up as it seems that others have been confused in the past.

**Comment by ryanpitts1** [comment]
@summera What did you figure out about this? The docs are kinda confusing.

@Skaelv If we're using the api_key and app_id like this: `Intercom::Client.new(api_key: IntercomRails.config.api_key, app_id: IntercomRails.config.app_id)` do we need to change it to use the new access_token?

**Comment by kavalenka** [comment]
@summera hi!
Could you please help me?
Have the same issue, received mail with Api keys deprecation.
I use secret key to enable "Identity Verification"

So what's the solution? Should key be replaced with token? If true, how should I do it?
Thanks!

**Comment by summera** [comment]
@kavalenka The "api secret" used for web verification and what you configure this gem with is different from the api key and secret that is being deprecated. If you've got the gem configured with the identity verification secret key then you should be all good and there is nothing to do.

**Comment by kavalenka** [comment]
@summera Great! Thanks!
