### ISSUE TITLE
Regarding the email notification from Intercom

### ISSUE THREAD

**Issue by kurianic** [intercom/intercom-rails#284]
@Skaelv  I am a little bit confused about the API key deprecation email from Intercome. Do I need to replace my app secret with the new access token?  I am using functions like create event and get user info. Thanks in advance.

**Comment by dakotahp** [comment]
I am also confused. The [guide on migrating](https://developers.intercom.com/v2.0/docs/replacing-your-api-keys-with-access-tokens-step-by-step-guide#section-step-2-replace-your-api-keys) seems to not clearly correlate to the gem which only mentions an API secret. The guide mentions:

> API Keys had a username/password format, but Access Tokens do not use this format. You have two options when replacing your API Keys:
> 1. Continue using the username/password format, leaving the password field blank

Whereas the gem says:
> If you want to use Identity Verification, ensure you set your API secret in config/initializers/intercom.rb

I've tried different permutations but there seems to be no correlation between the two instructions.

**Comment by kmossco** [comment]
@kurianic and @dakotahp, the API key deprecation is only relevant for the server-side integration with Intercom's [REST API](https://developers.intercom.com/v2.0/reference) that before allowed you to use API Keys and now requires you migrate or use Access Tokens for authentication.

This gem, because it only works by injecting the client-side Messenger on your page, uses what we call the API secret but that refers to the Identity Verification secret key as explained here: https://developers.intercom.com/docs/enable-secure-mode-on-your-web-product.

So no action needed on your integration of this gem. 👍

**Comment by dakotahp** [comment]
Thank you for clarifying!
