### ISSUE TITLE
How do I hide the intercom widget? 

### ISSUE THREAD

**Issue by kandadaboggu** [intercom/intercom-rails#89]
I want to use the Intercom script to monitor user activity, but I want to hide the Intercom Messenger displayed in the page. Is there a configuration for it in the gem?

**Comment by taciomedeiros** [comment]
to disable the button chat !
![update](https://cloud.githubusercontent.com/assets/5381694/10691752/5335bf2e-796a-11e5-9499-af13451be175.png)

**Comment by deepakcoreapps** [comment]
how to display messanger button in android applicaton

**Comment by antwonlee** [comment]
Is there way to to hide on certain pages?

something like: 

`Intercom('hide);`

**Comment by BatesJernigan** [comment]
@antwonlee the command you're looking for is
https://github.com/intercom/intercom-rails#disabling-automatic-insertion

**Comment by hankish** [comment]
@BatesJernigan: In my case I need to hide the intercom widget but this structure won't work for me. I've got an action (ex: users_controller#show) with multiple formats. One of the formats is "embed" which generates an iframe-embeddable version of the user's profile. I want to prevent the intercom widget from showing up in the embedded iframe, but if I prevent it for the whole show action then it won't show up on normal user pages.  Does that make sense?  

Is there any way for me to selectively disable the widget from within the code of the action itself rather than having to use a controller filter that wipes it out for the entire action?

**Comment by amowu** [comment]
```
Intercom('update', {"
  hide_default_launcher": false
});
```

https://www.intercom.com/help/en/articles/189-turn-off-show-or-hide-the-intercom-messenger

**Comment by spjpgrd** [comment]
> ```js
> ```js
> Intercom('update', {"
>   hide_default_launcher": true
> });
> ```
> 
> 
> https://www.intercom.com/help/en/articles/189-turn-off-show-or-hide-the-intercom-messenger
> ```

While this is correct, watch out for throttling:

> Update Throttling
> You can call Intercom('update') without getting throttled up to 20 times per 30 minutes. After the 20th call, you'll be throttled and the quota of 20 calls will get reset every 30 minutes. Reloading the page will refresh this state.

_[from Intercom Documentation](https://developers.intercom.com/installing-intercom/docs/intercom-javascript#section-intercomupdate)_
